{
 "title": "Prometheus Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{route=\"transactions\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (flagged) (rate(transactions_processed_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_publish_errors_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}